```{r}
library(tidyverse)
library(stringi)
library(readxl)
library(xlsx)
source("C:/Users/napcc/Dropbox (CPI)/EduardoMinsky/PARAMIM/landuse_br2024/AuxFolder/Dictionary_Sectors.R")
setwd("A:\\projects\\landuse_br2024\\SIOP\\Clean_Data")

siop_tratado <- read_rds('Siop_Tratado_2015_2023_05_24.rds') #258.437 registros

#Tabelas relacionais
grupo_despesa <- read_excel("A:/projects/landuse_br2024/SIOP/12_siop_relational_tables.xlsx", sheet="grupo_despesa")
channel_landscape <- read_excel("A:/projects/landuse_br2024/SIOP/12_siop_relational_tables.xlsx", sheet="channel_landscape")
sector_landscape <- read_excel("A:/projects/landuse_br2024/SIOP/12_siop_relational_tables.xlsx", sheet="sector_landscape")
sector_landscape <- sector_landscape %>% mutate(acao_des_limpa = str_trim(str_to_lower(stri_trans_general(acao_des_orig,"Latin-ASCII"))))
sector_landscape <- sector_landscape %>%select(acao_des_limpa,sector_landscape)%>% distinct(acao_des_limpa,.keep_all=TRUE) 
sector_landscape %>% view
####################################################
source_landscape <- read_excel("A:/projects/landuse_br2024/SIOP/12_siop_relational_tables.xlsx", sheet="source_landscape")

source_landscape <- source_landscape%>%mutate(source_original = str_trim(str_to_lower(stri_trans_general(source_original,"Latin-ASCII"))))

instrument_landscape <- read_excel("A:/projects/landuse_br2024/SIOP/12_siop_relational_tables.xlsx", sheet="instrument_landscape")

climate_use <- read_excel("A:/projects/landuse_br2024/SIOP/12_siop_relational_tables.xlsx", sheet="climate_use")
climate_use <- climate_use %>% mutate(acao_des_limpa = str_trim(str_to_lower(stri_trans_general(acao_des,"Latin-ASCII"))))
climate_use$acao_des_limpa
######################################################################
# Filtrando as observações que nao pagaram nada
siop_tratado <- siop_tratado %>% filter(Pago != 0)
# Eliminando grupo de despesas que nao queremos
grupo_despesa %>% filter(select != 1) %>% select(grupo_despesa) %>% as.vector()

siop_tratado <- siop_tratado %>% filter(grupo_de_despesa != "juros e encargos da divida" & grupo_de_despesa!= "amortizacao da divida" & grupo_de_despesa != "reserva de contingencia") #141.998 registros

# Filtrando as Unidades Orçamentárias baseado no channel landscape:
siop_tratado_unidade_orcamentaria <- siop_tratado %>% inner_join(channel_landscape %>% filter(!is.na(und_orc)) %>% select(und_orc)%>% unique, by= "und_orc") 

# Criando o que não entrou de unidade orçamentaria -> df_remainder_SIOP1
df_remainder_SIOP1 <- siop_tratado %>% anti_join(siop_tratado_unidade_orcamentaria %>% select(und_orc )%>% unique, by= "und_orc") 

################################################################## RODAR APENAS UMA VEZ ESTAS LINHAS ################################################################################################
#siop_tratado_unidade_orcamentaria %>% group_by(modalidade,und_orc)%>% unique%>% count()%>% write_csv2("Modalidade_UnidadeOrcamentaria_SIOP_2015_2023_CriadoEm05_04_2023.csv")
######################################################################################################################################################################################################
#Filtrar as ações que compoem o sector landscape
siop_tratado_unidade_orcamentaria_acao <- siop_tratado_unidade_orcamentaria %>% inner_join(sector_landscape %>% select(acao_des_limpa),by = c("acao" = "acao_des_limpa")) #10.922 registros
df_remainder_siop2 <- siop_tratado_unidade_orcamentaria %>% anti_join(sector_landscape %>% select(acao_des_limpa),by = c("acao" = "acao_des_limpa"))
df_remainder_siop2 %>% select(programa,acao,plano_orc)%>% view

sector_landscape %>% anti_join(siop_tratado_unidade_orcamentaria,by = c("acao_des_limpa" = "acao")) %>% view # Todas as ações foram pegas
###################################### RODAR APENAS UMA VEZ ESSA PARTE############################################
acao_plan_orc_count <- read_excel("A:/projects/landuse_br2024/SIOP/12_siop_relational_tables.xlsx",sheet = "acao_plan_orc_filter")
acao_plan_orc_count_unique <- acao_plan_orc_count %>% mutate(plano_orc_clean = str_trim(str_to_lower(stri_trans_general(plano_orc_clean,"Latin-ASCII")),side="both")) %>% select(plano_orc_clean)%>%unique

siop_tratado_unidade_orcamentaria_acao_plano_orc <- siop_tratado_unidade_orcamentaria_acao %>%  filter(Ano >= 2015 & Ano <= 2020) %>% inner_join(acao_plan_orc_count_unique,by = c("plano_orc"="plano_orc_clean")) 

acao_plan_orc_count_unique %>% anti_join(siop_tratado_unidade_orcamentaria_acao_plano_orc,by = c("plano_orc_clean"="plano_orc")) %>% view #Sobrou nada
```

```{r Metodologia 1}
# Esta metodologia é o padrao, antes de ser proposto os filtros de ajuste
adm_unidades_filter <- siop_tratado_unidade_orcamentaria_acao_plano_orc %>% filter(acao == "administracao da unidade")  %>% filter(und_orc =="ministerio do meio ambiente e mudanca do clima - administracao direta"|und_orc == "instituto brasileiro do meio ambiente e dos recursos naturais renovaveis - ibama" | und_orc == "fundacao nacional do indio - funai" | und_orc == "instituto chico mendes de conservacao da biodiversidade" |  und_orc == "servico florestal brasileiro - sfb" | und_orc == "instituto de pesquisas jardim botanico do rio de janeiro - jbrj") 
resto <- siop_tratado_unidade_orcamentaria_acao_plano_orc%>% filter(acao != "administracao da unidade")

folha_pagamento <- resto %>% filter(acao == "assistencia medica e odontologica aos servidores civis, empregados, militares e seus dependentes"|
                   acao == "assistencia pre-escolar aos dependentes dos servidores civis, empregados e militares"|
                   acao == "auxilio-transporte aos servidores civis, empregados e militares"|
                   acao == "auxilio-alimentacao aos servidores civis, empregados e militares"|
                   acao == "beneficios assistenciais decorrentes do auxilio-funeral e natalidade"|
                   acao == "contribuicao da uniao, de suas autarquias e fundacoes para o custeio do regime de previdencia dos servidores publicos federais"|
                   acao=="ativos civis da uniao"| acao == "pagamento de pessoal ativo da uniao"|
                   acao == "pessoal ativo da uniao"| acao == "beneficios obrigatorios aos servidores civis, empregados, militares e seus dependentes"|
                   acao == "ajuda de custo para moradia ou auxilio-moradia a agentes publicos")

folha_pagamento_certo <- folha_pagamento %>% filter( und_orc == "instituto brasileiro do meio ambiente e dos recursos naturais renovaveis - ibama" |
                             und_orc == "fundacao nacional do indio - funai" | und_orc == "instituto chico mendes de conservacao da biodiversidade" |
                             und_orc == "servico florestal brasileiro - sfb" | und_orc=="ministerio do meio ambiente e mudanca do clima - administracao direta"|
                               und_orc == "instituto de pesquisas jardim botanico do rio de janeiro - jbrj") 

resto2 <- resto %>% anti_join(folha_pagamento)
data_siop_final <- bind_rows(adm_unidades_filter,resto2,folha_pagamento_certo)
data_siop_final$Pago %>% sum
# Valor total sem aplicar rio_marker: 23.382.689.848
# Inicio da Transformacao para o landscape
data_siop_final_landscape <- data_siop_final%>%
  mutate(id_original = "-",
         data_source = "siop_painel",
         year = Ano,
         project_name = acao,
         project_description = plano_orc,
         source_original = fonte_recursos) %>% left_join(source_landscape%>%select(fonte_recursos, source_finance_landscape, origin_domestic_international,origin_private_public),
                                                         by = "fonte_recursos") %>% 
  mutate(value_original_currency = Pago,
         original_currency = "BRL",
         channel_original = str_c(modalidade,und_orc,sep=";")) %>% left_join(channel_landscape %>% select(channel_original,channel_landscape),by = "channel_original") %>%
  mutate(instrument_original = grupo_de_despesa) %>% left_join(instrument_landscape, by ="instrument_original") %>% 
  mutate(sector_original = str_c(funcao,subfuncao,sep = ";")) %>% left_join(sector_landscape, by = c("acao" = "acao_des_limpa")) %>%
  mutate(subsector_original = programa)

#Filtro Climático
data_siop_final_landscape2 <- data_siop_final_landscape %>% left_join(climate_use %>% select(acao_des_limpa,rio_marker,climate_component ,activity_landscape ),by = c("acao"="acao_des_limpa")) 
# Filtro do Ajuste 5 (FOI APLICADO A AJUSTE 5 POIES ELE ESTA CERTO)
data_siop_final_landscape2 <- data_siop_final_landscape2 %>%
  mutate(rio_marker = case_when(plano_orc == "licenca, avaliacao , registro e autorizacoes ambientais" ~ 0.4,
                                plano_orc == "licenca, avaliacao, registro e autorizacoes ambientais" ~ 0.4,
                                plano_orc == "rastreio e controle de satelites" ~ 0.4,
                                plano_orc == "recepcao, armazenamento, processamento e distribuicao de dados de satelites"~0.4,
                                plano_orc == "apoio ao desenvolvimento sustentavel das cadeias produtivas agricolas"~0.4,
                                plano_orc == "fomento a indicacao geografica de produtos agropecuarios - ig"~0.4,
                                plano_orc == "funcionamento do conselho nacional de recursos hidricos"~0.4,
                                .default = rio_marker)) 
#Filtro de Ajuste 4 (FOI APLICADO O AJUSETE 4 POIS ELE ESTA CERTO TBM)
data_siop_final_landscape2 <- data_siop_final_landscape2 %>% 
  mutate(rio_marker = case_when(plano_orc=="desenvolvimento dos satelites da serie amazonia"~1,
                                plano_orc == "desenvolvimento dos satelites da serie amazonia - regra de ouro"~1,
                                .default = rio_marker)) 
  


data_siop_final_landscape2

# Aplicacao Rio Marker
data_siop_final_landscape2 <- data_siop_final_landscape2 %>% mutate(value_original_currency = value_original_currency*rio_marker)
data_siop_final_landscape2$value_original_currency %>% sum #22.491.876.433

# O valor esta parecido com a nossa 1a comparacao

```

```{r Metodologia 2}
# Esta metodologia aplica o Filtro para Unidade Administrativa e Folha de pagamento
adm_unidades_filter <- siop_tratado_unidade_orcamentaria_acao_plano_orc %>% filter(acao == "administracao da unidade")  %>% filter(und_orc =="ministerio do meio ambiente e mudanca do clima - administracao direta"|und_orc == "instituto brasileiro do meio ambiente e dos recursos naturais renovaveis - ibama" | und_orc == "fundacao nacional do indio - funai" | und_orc == "instituto chico mendes de conservacao da biodiversidade" |  und_orc == "servico florestal brasileiro - sfb" | und_orc == "instituto de pesquisas jardim botanico do rio de janeiro - jbrj")%>%
filter(plano_orc=="administracao da unidade" |plano_orc=="administracao da unidade - despesas diversas"|plano_orc=="administracao da unidade - despesas diversas - regra de ouro") # Esta de acordo com o Ajuste 1

# A partir de agora, vamos "excluir" QUALQUER UNIDADE ADMINISTRATIVA DA ANALISE, visto que já filtramos os planos orcs e unidades orcs
# da ação unidade administrativa
resto <- siop_tratado_unidade_orcamentaria_acao_plano_orc%>% filter(acao != "administracao da unidade")

# Aplicando Ajuste 2 e 3 ao mesmo tempo
folha_pagamento <- resto %>% filter(acao == "assistencia medica e odontologica aos servidores civis, empregados, militares e seus dependentes"|
                   acao == "assistencia pre-escolar aos dependentes dos servidores civis, empregados e militares"|
                   acao == "auxilio-transporte aos servidores civis, empregados e militares"|
                   acao == "auxilio-alimentacao aos servidores civis, empregados e militares"|
                   acao == "beneficios assistenciais decorrentes do auxilio-funeral e natalidade"|
                   acao == "contribuicao da uniao, de suas autarquias e fundacoes para o custeio do regime de previdencia dos servidores publicos federais"|
                   acao=="ativos civis da uniao"| acao == "pagamento de pessoal ativo da uniao"|
                   acao == "pessoal ativo da uniao"| acao == "beneficios obrigatorios aos servidores civis, empregados, militares e seus dependentes"|
                   acao == "ajuda de custo para moradia ou auxilio-moradia a agentes publicos")

# Aqui entra o Ajuste 2 e 3
folha_pagamento_certo <- folha_pagamento %>% filter( und_orc == "instituto brasileiro do meio ambiente e dos recursos naturais renovaveis - ibama" |
                             und_orc == "fundacao nacional do indio - funai" | und_orc == "instituto chico mendes de conservacao da biodiversidade" |
                             und_orc == "servico florestal brasileiro - sfb" | und_orc=="ministerio do meio ambiente e mudanca do clima - administracao direta"|
                               und_orc == "instituto de pesquisas jardim botanico do rio de janeiro - jbrj") %>% filter(plano_orc == "ajuda de custo para moradia ou auxilio-moradia a agentes publicos"|
             plano_orc == "ajuda de custo para moradia ou auxilio-moradia a agentes publicos - despesas diversas"|
             plano_orc == "assistencia medica e odontologica aos servidores civis, empregados, militares e seus dependentes"|
             plano_orc == "assistencia medica e odontologica de civis - complementacao da uniao"|
             plano_orc == "assistencia medica e odontologica de civis - complementacao da uniao"|
             plano_orc == "assistencia pre-escolar aos dependentes dos servidores civis e de empregados"|
             plano_orc == "assistencia pre-escolar aos dependentes dos servidores civis e de empregados"|
             plano_orc == "auxilio-alimentacao aos servidores civis, empregados e militares"|
             plano_orc == "auxilio-transporte aos servidores civis, empregados e militares"|
             plano_orc == "regra de ouro: assistencia medica e odontologica de civis - complementacao da uniao"|
             plano_orc == "regra de ouro: assistencia medica e odontologica de civis - complementacao da uniao"|
             plano_orc == "auxilio-alimentacao de civis"|
             plano_orc== "ajuda de custo para moradia ou auxilio-moradia a agentes publicos"|
             plano_orc == "capacitacao de servidores publicos federais em processo de qualificacao e requalificacao"|
             plano_orc == "capacitacao de servidores publicos federais em processo de qualificacao e requalificacao - regra de ouro"|
             plano_orc == "capacitacao de servidores publicos federais em processo de qualificacao e requalificacao - area fim"|
             plano_orc == "capacitacao de servidores publicos federais em processo de qualificacao e requalificacao - area meio")




folha_pagamento %>% filter(acao == "beneficios assistenciais decorrentes do auxilio-funeral e natalidade")%>% filter( und_orc == "instituto brasileiro do meio ambiente e dos recursos naturais renovaveis - ibama" |
                             und_orc == "fundacao nacional do indio - funai" | und_orc == "instituto chico mendes de conservacao da biodiversidade" |
                             und_orc == "servico florestal brasileiro - sfb" | und_orc=="ministerio do meio ambiente e mudanca do clima - administracao direta"|
                               und_orc == "instituto de pesquisas jardim botanico do rio de janeiro - jbrj") %>% select(und_orc,plano_orc) %>% unique

# Observa-se que:
# Sem observacao para a acao auxilio-transporte aos servidores civis, empregados e militares  
# sem observacao para a acao beneficios assistenciais decorrentes do auxilio-funeral e natalidade
# sem observacao para a acao contribuicao da uniao, de suas autarquias e fundacoes para o custeio do regime de previdencia dos servidores publicos federais
# sem observacao para a acao ativos civis da uniao
# Sem observacao para a acao pagamento de pessoal ativo da uniao
# sem observacao para a acao pessoal ativo da uniao
resto2 <- resto %>% anti_join(folha_pagamento)
data_siop_final <- bind_rows(adm_unidades_filter,resto2,folha_pagamento_certo)
data_siop_final$Pago %>% sum
#Valor sem rio_marker 15.385.472.486
# Inicio da Transformacao para o landscape
data_siop_final_landscape <- data_siop_final%>%
  mutate(id_original = "-",
         data_source = "siop_painel",
         year = Ano,
         project_name = acao,
         project_description = plano_orc,
         source_original = fonte_recursos) %>% left_join(source_landscape%>%select(fonte_recursos, source_finance_landscape, origin_domestic_international,origin_private_public),
                                                         by = "fonte_recursos") %>% 
  mutate(value_original_currency = Pago,
         original_currency = "BRL",
         channel_original = str_c(modalidade,und_orc,sep=";")) %>% left_join(channel_landscape %>% select(channel_original,channel_landscape),by = "channel_original") %>%
  mutate(instrument_original = grupo_de_despesa) %>% left_join(instrument_landscape, by ="instrument_original") %>% 
  mutate(sector_original = str_c(funcao,subfuncao,sep = ";")) %>% left_join(sector_landscape, by = c("acao" = "acao_des_limpa")) %>%
  mutate(subsector_original = programa)

#Filtro Climático
data_siop_final_landscape2 <- data_siop_final_landscape %>% left_join(climate_use %>% select(acao_des_limpa,rio_marker,climate_component ,activity_landscape ),by = c("acao"="acao_des_limpa")) 
# Filtro do Ajuste 5 (FOI APLICADO A AJUSTE 5 POIES ELE ESTA CERTO)
data_siop_final_landscape2 <- data_siop_final_landscape2 %>%
  mutate(rio_marker = case_when(plano_orc == "licenca, avaliacao , registro e autorizacoes ambientais" ~ 0.4,
                                plano_orc == "licenca, avaliacao, registro e autorizacoes ambientais" ~ 0.4,
                                plano_orc == "rastreio e controle de satelites" ~ 0.4,
                                plano_orc == "recepcao, armazenamento, processamento e distribuicao de dados de satelites"~0.4,
                                plano_orc == "apoio ao desenvolvimento sustentavel das cadeias produtivas agricolas"~0.4,
                                plano_orc == "fomento a indicacao geografica de produtos agropecuarios - ig"~0.4,
                                plano_orc == "funcionamento do conselho nacional de recursos hidricos"~0.4,
                                .default = rio_marker)) 
#Filtro de Ajuste 4 (FOI APLICADO O AJUSETE 4 POIS ELE ESTA CERTO TBM)
data_siop_final_landscape2 <- data_siop_final_landscape2 %>% 
  mutate(rio_marker = case_when(plano_orc=="desenvolvimento dos satelites da serie amazonia"~1,
                                plano_orc == "desenvolvimento dos satelites da serie amazonia - regra de ouro"~1,
                                .default = rio_marker)) 
  


data_siop_final_landscape2

# Aplicacao Rio Marker
data_siop_final_landscape2 <- data_siop_final_landscape2 %>% mutate(value_original_currency = value_original_currency*rio_marker)
data_siop_final_landscape2$value_original_currency %>% sum #14.494.659.071

# Alguns outros problemas dessa metodologia:
# Planos orcamentarios, como do INPE, foram embora
# Não há Administração da Unidade;Capacitação de Recursos Humanos no INPE
data_siop_final_landscape2 %>% filter(acao == "administracao da unidade") %>% select(plano_orc) %>% unique %>% view
```

```{r Metodologia 3 - Algumas soluções}
# Esta metodologia visa ter um match maior com a base publicada

adm_unidades_filter <- siop_tratado_unidade_orcamentaria_acao_plano_orc %>% filter(acao == "administracao da unidade")  %>% filter(und_orc =="ministerio do meio ambiente e mudanca do clima - administracao direta"|und_orc == "instituto brasileiro do meio ambiente e dos recursos naturais renovaveis - ibama" | und_orc == "fundacao nacional do indio - funai" | und_orc == "instituto chico mendes de conservacao da biodiversidade" |  und_orc == "servico florestal brasileiro - sfb" | und_orc == "instituto de pesquisas jardim botanico do rio de janeiro - jbrj")%>%
filter(plano_orc=="administracao da unidade" |plano_orc=="administracao da unidade - despesas diversas"|plano_orc=="administracao da unidade - despesas diversas - regra de ouro") # Esta de acordo com o Ajuste 1

# A PRIMEIRA MUDANÇA É AQUI. VAMOS EXCLUIR DO RESTO APENAS AS ADMINISTRAÇÕES DA UNIDADE QUE NÓS PEGAMOS

resto <- siop_tratado_unidade_orcamentaria_acao_plano_orc%>% anti_join(adm_unidades_filter)

# Mantem-se o resto como esta
# Aplicando Ajuste 2 e 3 ao mesmo tempo
folha_pagamento <- resto %>% filter(acao == "assistencia medica e odontologica aos servidores civis, empregados, militares e seus dependentes"|
                   acao == "assistencia pre-escolar aos dependentes dos servidores civis, empregados e militares"|
                   acao == "auxilio-transporte aos servidores civis, empregados e militares"|
                   acao == "auxilio-alimentacao aos servidores civis, empregados e militares"|
                   acao == "beneficios assistenciais decorrentes do auxilio-funeral e natalidade"|
                   acao == "contribuicao da uniao, de suas autarquias e fundacoes para o custeio do regime de previdencia dos servidores publicos federais"|
                   acao=="ativos civis da uniao"| acao == "pagamento de pessoal ativo da uniao"|
                   acao == "pessoal ativo da uniao"| acao == "beneficios obrigatorios aos servidores civis, empregados, militares e seus dependentes"|
                   acao == "ajuda de custo para moradia ou auxilio-moradia a agentes publicos")

# Aqui entra o Ajuste 2 e 3
folha_pagamento_certo <- folha_pagamento %>% filter( und_orc == "instituto brasileiro do meio ambiente e dos recursos naturais renovaveis - ibama" |
                             und_orc == "fundacao nacional do indio - funai" | und_orc == "instituto chico mendes de conservacao da biodiversidade" |
                             und_orc == "servico florestal brasileiro - sfb" | und_orc=="ministerio do meio ambiente e mudanca do clima - administracao direta"|
                               und_orc == "instituto de pesquisas jardim botanico do rio de janeiro - jbrj") %>% filter(plano_orc == "ajuda de custo para moradia ou auxilio-moradia a agentes publicos"|
             plano_orc == "ajuda de custo para moradia ou auxilio-moradia a agentes publicos - despesas diversas"|
             plano_orc == "assistencia medica e odontologica aos servidores civis, empregados, militares e seus dependentes"|
             plano_orc == "assistencia medica e odontologica de civis - complementacao da uniao"|
             plano_orc == "assistencia medica e odontologica de civis - complementacao da uniao"|
             plano_orc == "assistencia pre-escolar aos dependentes dos servidores civis e de empregados"|
             plano_orc == "assistencia pre-escolar aos dependentes dos servidores civis e de empregados"|
             plano_orc == "auxilio-alimentacao aos servidores civis, empregados e militares"|
             plano_orc == "auxilio-transporte aos servidores civis, empregados e militares"|
             plano_orc == "regra de ouro: assistencia medica e odontologica de civis - complementacao da uniao"|
             plano_orc == "regra de ouro: assistencia medica e odontologica de civis - complementacao da uniao"|
             plano_orc == "auxilio-alimentacao de civis"|
             plano_orc== "ajuda de custo para moradia ou auxilio-moradia a agentes publicos"|
             plano_orc == "capacitacao de servidores publicos federais em processo de qualificacao e requalificacao"|
             plano_orc == "capacitacao de servidores publicos federais em processo de qualificacao e requalificacao - regra de ouro"|
             plano_orc == "capacitacao de servidores publicos federais em processo de qualificacao e requalificacao - area fim"|
             plano_orc == "capacitacao de servidores publicos federais em processo de qualificacao e requalificacao - area meio")



#AINDA TEREMOS O MESMO PROBLEMA AQUI DAS FOLHAS DE PAG.
folha_pagamento %>% filter(acao == "beneficios assistenciais decorrentes do auxilio-funeral e natalidade")%>% filter( und_orc == "instituto brasileiro do meio ambiente e dos recursos naturais renovaveis - ibama" |
                             und_orc == "fundacao nacional do indio - funai" | und_orc == "instituto chico mendes de conservacao da biodiversidade" |
                             und_orc == "servico florestal brasileiro - sfb" | und_orc=="ministerio do meio ambiente e mudanca do clima - administracao direta"|
                               und_orc == "instituto de pesquisas jardim botanico do rio de janeiro - jbrj") %>% select(und_orc,plano_orc) %>% unique

# Observa-se que:
# Sem observacao para a acao auxilio-transporte aos servidores civis, empregados e militares  
# sem observacao para a acao beneficios assistenciais decorrentes do auxilio-funeral e natalidade
# sem observacao para a acao contribuicao da uniao, de suas autarquias e fundacoes para o custeio do regime de previdencia dos servidores publicos federais
# sem observacao para a acao ativos civis da uniao
# Sem observacao para a acao pagamento de pessoal ativo da uniao
# sem observacao para a acao pessoal ativo da uniao
resto2 <- resto %>% anti_join(folha_pagamento)
data_siop_final <- bind_rows(adm_unidades_filter,resto2,folha_pagamento_certo)
data_siop_final$Pago %>% sum
#Valor sem rio_marker 15.385.472.486
# Inicio da Transformacao para o landscape
data_siop_final_landscape <- data_siop_final%>%
  mutate(id_original = "-",
         data_source = "siop_painel",
         year = Ano,
         project_name = acao,
         project_description = plano_orc,
         source_original = fonte_recursos) %>% left_join(source_landscape%>%select(fonte_recursos, source_finance_landscape, origin_domestic_international,origin_private_public),
                                                         by = "fonte_recursos") %>% 
  mutate(value_original_currency = Pago,
         original_currency = "BRL",
         channel_original = str_c(modalidade,und_orc,sep=";")) %>% left_join(channel_landscape %>% select(channel_original,channel_landscape),by = "channel_original") %>%
  mutate(instrument_original = grupo_de_despesa) %>% left_join(instrument_landscape, by ="instrument_original") %>% 
  mutate(sector_original = str_c(funcao,subfuncao,sep = ";")) %>% left_join(sector_landscape, by = c("acao" = "acao_des_limpa")) %>%
  mutate(subsector_original = programa)

#Filtro Climático
data_siop_final_landscape2 <- data_siop_final_landscape %>% left_join(climate_use %>% select(acao_des_limpa,rio_marker,climate_component ,activity_landscape ),by = c("acao"="acao_des_limpa")) 
# Filtro do Ajuste 5 (FOI APLICADO A AJUSTE 5 POIES ELE ESTA CERTO)
data_siop_final_landscape2 <- data_siop_final_landscape2 %>%
  mutate(rio_marker = case_when(plano_orc == "licenca, avaliacao , registro e autorizacoes ambientais" ~ 0.4,
                                plano_orc == "licenca, avaliacao, registro e autorizacoes ambientais" ~ 0.4,
                                plano_orc == "rastreio e controle de satelites" ~ 0.4,
                                plano_orc == "recepcao, armazenamento, processamento e distribuicao de dados de satelites"~0.4,
                                plano_orc == "apoio ao desenvolvimento sustentavel das cadeias produtivas agricolas"~0.4,
                                plano_orc == "fomento a indicacao geografica de produtos agropecuarios - ig"~0.4,
                                plano_orc == "funcionamento do conselho nacional de recursos hidricos"~0.4,
                                .default = rio_marker)) 
#Filtro de Ajuste 4 (FOI APLICADO O AJUSETE 4 POIS ELE ESTA CERTO TBM)
data_siop_final_landscape2 <- data_siop_final_landscape2 %>% 
  mutate(rio_marker = case_when(plano_orc=="desenvolvimento dos satelites da serie amazonia"~1,
                                plano_orc == "desenvolvimento dos satelites da serie amazonia - regra de ouro"~1,
                                .default = rio_marker)) 
  


data_siop_final_landscape2

# Aplicacao Rio Marker
data_siop_final_landscape2 <- data_siop_final_landscape2 %>% mutate(value_original_currency = value_original_currency*rio_marker)
data_siop_final_landscape2$value_original_currency %>% sum #16.557.046.561

# Alguns outros problemas dessa metodologia:
# Planos orcamentarios, como do INPE, foram embora
# Não há Administração da Unidade;Capacitação de Recursos Humanos no INPE
data_siop_final_landscape2 %>% filter(acao == "administracao da unidade") %>% select(plano_orc) %>% unique %>% view
# Ja esta um pouco melhor
```

```{r Metodologia 4 - Outras soluções}
# Esta metodologia visa ter um match maior com a base publicada

adm_unidades_filter <- siop_tratado_unidade_orcamentaria_acao_plano_orc %>% filter(acao == "administracao da unidade")  %>% filter(und_orc =="ministerio do meio ambiente e mudanca do clima - administracao direta"|und_orc == "instituto brasileiro do meio ambiente e dos recursos naturais renovaveis - ibama" | und_orc == "fundacao nacional do indio - funai" | und_orc == "instituto chico mendes de conservacao da biodiversidade" |  und_orc == "servico florestal brasileiro - sfb" | und_orc == "instituto de pesquisas jardim botanico do rio de janeiro - jbrj")%>%
filter(plano_orc=="administracao da unidade" |plano_orc=="administracao da unidade - despesas diversas"|plano_orc=="administracao da unidade - despesas diversas - regra de ouro") # Esta de acordo com o Ajuste 1

# A PRIMEIRA MUDANÇA É AQUI. VAMOS EXCLUIR DO RESTO APENAS AS ADMINISTRAÇÕES DA UNIDADE QUE NÓS PEGAMOS

resto <- siop_tratado_unidade_orcamentaria_acao_plano_orc%>% anti_join(adm_unidades_filter)

# Mantem-se o resto como esta
# Aplicando Ajuste 2 e 3 ao mesmo tempo
folha_pagamento <- resto %>% filter(acao == "assistencia medica e odontologica aos servidores civis, empregados, militares e seus dependentes"|
                   acao == "assistencia pre-escolar aos dependentes dos servidores civis, empregados e militares"|
                   acao == "auxilio-transporte aos servidores civis, empregados e militares"|
                   acao == "auxilio-alimentacao aos servidores civis, empregados e militares"|
                   acao == "beneficios assistenciais decorrentes do auxilio-funeral e natalidade"|
                   acao == "contribuicao da uniao, de suas autarquias e fundacoes para o custeio do regime de previdencia dos servidores publicos federais"|
                   acao=="ativos civis da uniao"| acao == "pagamento de pessoal ativo da uniao"|
                   acao == "pessoal ativo da uniao"| acao == "beneficios obrigatorios aos servidores civis, empregados, militares e seus dependentes"|
                   acao == "ajuda de custo para moradia ou auxilio-moradia a agentes publicos")

# Aqui entra o Ajuste 2 e 3
folha_pagamento_certo <- folha_pagamento %>% filter( und_orc == "instituto brasileiro do meio ambiente e dos recursos naturais renovaveis - ibama" |
                             und_orc == "fundacao nacional do indio - funai" | und_orc == "instituto chico mendes de conservacao da biodiversidade" |
                             und_orc == "servico florestal brasileiro - sfb" | und_orc=="ministerio do meio ambiente e mudanca do clima - administracao direta"|
                               und_orc == "instituto de pesquisas jardim botanico do rio de janeiro - jbrj") %>% filter(plano_orc == "ajuda de custo para moradia ou auxilio-moradia a agentes publicos"|
             plano_orc == "ajuda de custo para moradia ou auxilio-moradia a agentes publicos - despesas diversas"|
             plano_orc == "assistencia medica e odontologica aos servidores civis, empregados, militares e seus dependentes"|
             plano_orc == "assistencia medica e odontologica de civis - complementacao da uniao"|
             plano_orc == "assistencia medica e odontologica de civis - complementacao da uniao"|
             plano_orc == "assistencia pre-escolar aos dependentes dos servidores civis e de empregados"|
             plano_orc == "assistencia pre-escolar aos dependentes dos servidores civis e de empregados"|
             plano_orc == "auxilio-alimentacao aos servidores civis, empregados e militares"|
             plano_orc == "auxilio-transporte aos servidores civis, empregados e militares"|
             plano_orc == "regra de ouro: assistencia medica e odontologica de civis - complementacao da uniao"|
             plano_orc == "regra de ouro: assistencia medica e odontologica de civis - complementacao da uniao"|
             plano_orc == "auxilio-alimentacao de civis"|
             plano_orc== "ajuda de custo para moradia ou auxilio-moradia a agentes publicos"|
             plano_orc == "capacitacao de servidores publicos federais em processo de qualificacao e requalificacao"|
             plano_orc == "capacitacao de servidores publicos federais em processo de qualificacao e requalificacao - regra de ouro"|
             plano_orc == "capacitacao de servidores publicos federais em processo de qualificacao e requalificacao - area fim"|
             plano_orc == "capacitacao de servidores publicos federais em processo de qualificacao e requalificacao - area meio")



#AINDA TEREMOS O MESMO PROBLEMA AQUI DAS FOLHAS DE PAG.
folha_pagamento %>% filter(acao == "beneficios assistenciais decorrentes do auxilio-funeral e natalidade")%>% filter( und_orc == "instituto brasileiro do meio ambiente e dos recursos naturais renovaveis - ibama" |
                             und_orc == "fundacao nacional do indio - funai" | und_orc == "instituto chico mendes de conservacao da biodiversidade" |
                             und_orc == "servico florestal brasileiro - sfb" | und_orc=="ministerio do meio ambiente e mudanca do clima - administracao direta"|
                               und_orc == "instituto de pesquisas jardim botanico do rio de janeiro - jbrj") %>% select(und_orc,plano_orc) %>% unique

# Observa-se que:
# Sem observacao para a acao auxilio-transporte aos servidores civis, empregados e militares  
# sem observacao para a acao beneficios assistenciais decorrentes do auxilio-funeral e natalidade
# sem observacao para a acao contribuicao da uniao, de suas autarquias e fundacoes para o custeio do regime de previdencia dos servidores publicos federais
# sem observacao para a acao ativos civis da uniao
# Sem observacao para a acao pagamento de pessoal ativo da uniao
# sem observacao para a acao pessoal ativo da uniao

#A OUTRA MUDANÇA É AQUI: Vamos eliminar apenas as folhas de pagamento certo 
resto2 <- resto %>% anti_join(folha_pagamento_certo)
data_siop_final <- bind_rows(adm_unidades_filter,resto2,folha_pagamento_certo)
data_siop_final$Pago %>% sum
#Valor sem rio_marker 81.554.457.899 VALOR EXPLODE
# Inicio da Transformacao para o landscape
data_siop_final_landscape <- data_siop_final%>%
  mutate(id_original = "-",
         data_source = "siop_painel",
         year = Ano,
         project_name = acao,
         project_description = plano_orc,
         source_original = fonte_recursos) %>% left_join(source_landscape%>%select(fonte_recursos, source_finance_landscape, origin_domestic_international,origin_private_public),
                                                         by = "fonte_recursos") %>% 
  mutate(value_original_currency = Pago,
         original_currency = "BRL",
         channel_original = str_c(modalidade,und_orc,sep=";")) %>% left_join(channel_landscape %>% select(channel_original,channel_landscape),by = "channel_original") %>%
  mutate(instrument_original = grupo_de_despesa) %>% left_join(instrument_landscape, by ="instrument_original") %>% 
  mutate(sector_original = str_c(funcao,subfuncao,sep = ";")) %>% left_join(sector_landscape, by = c("acao" = "acao_des_limpa")) %>%
  mutate(subsector_original = programa)

#Filtro Climático
data_siop_final_landscape2 <- data_siop_final_landscape %>% left_join(climate_use %>% select(acao_des_limpa,rio_marker,climate_component ,activity_landscape ),by = c("acao"="acao_des_limpa")) 
# Filtro do Ajuste 5 (FOI APLICADO A AJUSTE 5 POIES ELE ESTA CERTO)
data_siop_final_landscape2 <- data_siop_final_landscape2 %>%
  mutate(rio_marker = case_when(plano_orc == "licenca, avaliacao , registro e autorizacoes ambientais" ~ 0.4,
                                plano_orc == "licenca, avaliacao, registro e autorizacoes ambientais" ~ 0.4,
                                plano_orc == "rastreio e controle de satelites" ~ 0.4,
                                plano_orc == "recepcao, armazenamento, processamento e distribuicao de dados de satelites"~0.4,
                                plano_orc == "apoio ao desenvolvimento sustentavel das cadeias produtivas agricolas"~0.4,
                                plano_orc == "fomento a indicacao geografica de produtos agropecuarios - ig"~0.4,
                                plano_orc == "funcionamento do conselho nacional de recursos hidricos"~0.4,
                                .default = rio_marker)) 
#Filtro de Ajuste 4 (FOI APLICADO O AJUSETE 4 POIS ELE ESTA CERTO TBM)
data_siop_final_landscape2 <- data_siop_final_landscape2 %>% 
  mutate(rio_marker = case_when(plano_orc=="desenvolvimento dos satelites da serie amazonia"~1,
                                plano_orc == "desenvolvimento dos satelites da serie amazonia - regra de ouro"~1,
                                .default = rio_marker)) 
  


data_siop_final_landscape2

# Aplicacao Rio Marker
data_siop_final_landscape2 <- data_siop_final_landscape2 %>% mutate(value_original_currency = value_original_currency*rio_marker)
data_siop_final_landscape2$value_original_currency %>% sum #80.307.319.118 VALOR EXPLODE

# Alguns outros problemas dessa metodologia:
# Planos orcamentarios, como do INPE, foram embora
# Não há Administração da Unidade;Capacitação de Recursos Humanos no INPE
data_siop_final_landscape2 %>% filter(acao == "administracao da unidade") %>% select(plano_orc) %>% unique %>% view

```

```{r Metodologia 5 - Ultima solucao explorada}
# Esta metodologia visa ter um match maior com a base publicada

adm_unidades_filter <- siop_tratado_unidade_orcamentaria_acao_plano_orc %>% filter(acao == "administracao da unidade")  %>% filter(und_orc =="ministerio do meio ambiente e mudanca do clima - administracao direta"|und_orc == "instituto brasileiro do meio ambiente e dos recursos naturais renovaveis - ibama" | und_orc == "fundacao nacional do indio - funai" | und_orc == "instituto chico mendes de conservacao da biodiversidade" |  und_orc == "servico florestal brasileiro - sfb" | und_orc == "instituto de pesquisas jardim botanico do rio de janeiro - jbrj")# A MUDANCA ESTA BEM AQUI!!!
# retirar a 2a parte do ajuste 1



# A PRIMEIRA MUDANÇA É AQUI. VAMOS EXCLUIR DO RESTO APENAS AS ADMINISTRAÇÕES DA UNIDADE QUE NÓS PEGAMOS

resto <- siop_tratado_unidade_orcamentaria_acao_plano_orc %>% anti_join(adm_unidades_filter)

# Mantem-se o resto como esta
# Aplicando Ajuste 2 e 3 ao mesmo tempo
folha_pagamento <- resto %>% filter(acao == "assistencia medica e odontologica aos servidores civis, empregados, militares e seus dependentes"|
                   acao == "assistencia pre-escolar aos dependentes dos servidores civis, empregados e militares"|
                   acao == "auxilio-transporte aos servidores civis, empregados e militares"|
                   acao == "auxilio-alimentacao aos servidores civis, empregados e militares"|
                   acao == "beneficios assistenciais decorrentes do auxilio-funeral e natalidade"|
                   acao == "contribuicao da uniao, de suas autarquias e fundacoes para o custeio do regime de previdencia dos servidores publicos federais"|
                   acao=="ativos civis da uniao"| acao == "pagamento de pessoal ativo da uniao"|
                   acao == "pessoal ativo da uniao"| acao == "beneficios obrigatorios aos servidores civis, empregados, militares e seus dependentes"|
                   acao == "ajuda de custo para moradia ou auxilio-moradia a agentes publicos")

# Aqui entra o Ajuste 2 e 3
folha_pagamento_certo <- folha_pagamento %>% filter( und_orc == "instituto brasileiro do meio ambiente e dos recursos naturais renovaveis - ibama" |
                             und_orc == "fundacao nacional do indio - funai" | und_orc == "instituto chico mendes de conservacao da biodiversidade" |
                             und_orc == "servico florestal brasileiro - sfb" | und_orc=="ministerio do meio ambiente e mudanca do clima - administracao direta"|
                               und_orc == "instituto de pesquisas jardim botanico do rio de janeiro - jbrj") %>% filter(plano_orc == "ajuda de custo para moradia ou auxilio-moradia a agentes publicos"|
             plano_orc == "ajuda de custo para moradia ou auxilio-moradia a agentes publicos - despesas diversas"|
             plano_orc == "assistencia medica e odontologica aos servidores civis, empregados, militares e seus dependentes"|
             plano_orc == "assistencia medica e odontologica de civis - complementacao da uniao"|
             plano_orc == "assistencia medica e odontologica de civis - complementacao da uniao"|
             plano_orc == "assistencia pre-escolar aos dependentes dos servidores civis e de empregados"|
             plano_orc == "assistencia pre-escolar aos dependentes dos servidores civis e de empregados"|
             plano_orc == "auxilio-alimentacao aos servidores civis, empregados e militares"|
             plano_orc == "auxilio-transporte aos servidores civis, empregados e militares"|
             plano_orc == "regra de ouro: assistencia medica e odontologica de civis - complementacao da uniao"|
             plano_orc == "regra de ouro: assistencia medica e odontologica de civis - complementacao da uniao"|
             plano_orc == "auxilio-alimentacao de civis"|
             plano_orc== "ajuda de custo para moradia ou auxilio-moradia a agentes publicos"|
             plano_orc == "capacitacao de servidores publicos federais em processo de qualificacao e requalificacao"|
             plano_orc == "capacitacao de servidores publicos federais em processo de qualificacao e requalificacao - regra de ouro"|
             plano_orc == "capacitacao de servidores publicos federais em processo de qualificacao e requalificacao - area fim"|
             plano_orc == "capacitacao de servidores publicos federais em processo de qualificacao e requalificacao - area meio")




folha_pagamento %>% filter(acao == "beneficios assistenciais decorrentes do auxilio-funeral e natalidade")%>% filter( und_orc == "instituto brasileiro do meio ambiente e dos recursos naturais renovaveis - ibama" |
                             und_orc == "fundacao nacional do indio - funai" | und_orc == "instituto chico mendes de conservacao da biodiversidade" |
                             und_orc == "servico florestal brasileiro - sfb" | und_orc=="ministerio do meio ambiente e mudanca do clima - administracao direta"|
                               und_orc == "instituto de pesquisas jardim botanico do rio de janeiro - jbrj") %>% select(und_orc,plano_orc) %>% unique

# Observa-se que:
# Sem observacao para a acao auxilio-transporte aos servidores civis, empregados e militares  
# sem observacao para a acao beneficios assistenciais decorrentes do auxilio-funeral e natalidade
# sem observacao para a acao contribuicao da uniao, de suas autarquias e fundacoes para o custeio do regime de previdencia dos servidores publicos federais
# sem observacao para a acao ativos civis da uniao
# Sem observacao para a acao pagamento de pessoal ativo da uniao
# sem observacao para a acao pessoal ativo da uniao

#A OUTRA MUDANÇA É AQUI: EXCLUIR TDAS AS FOLHAS DE PAGAMENTO
resto2 <- resto %>% anti_join(folha_pagamento)
data_siop_final <- bind_rows(adm_unidades_filter,resto2,folha_pagamento_certo)
data_siop_final$Pago %>% sum
#Valor sem rio_marker 17.804.185.342
# Inicio da Transformacao para o landscape
data_siop_final_landscape <- data_siop_final%>%
  mutate(id_original = "-",
         data_source = "siop_painel",
         year = Ano,
         project_name = acao,
         project_description = plano_orc,
         source_original = fonte_recursos) %>% left_join(source_landscape%>%select(fonte_recursos, source_finance_landscape, origin_domestic_international,origin_private_public),
                                                         by = "fonte_recursos") %>% 
  mutate(value_original_currency = Pago,
         original_currency = "BRL",
         channel_original = str_c(modalidade,und_orc,sep=";")) %>% left_join(channel_landscape %>% select(channel_original,channel_landscape),by = "channel_original") %>%
  mutate(instrument_original = grupo_de_despesa) %>% left_join(instrument_landscape, by ="instrument_original") %>% 
  mutate(sector_original = str_c(funcao,subfuncao,sep = ";")) %>% left_join(sector_landscape, by = c("acao" = "acao_des_limpa")) %>%
  mutate(subsector_original = programa)

#Filtro Climático
data_siop_final_landscape2 <- data_siop_final_landscape %>% left_join(climate_use %>% select(acao_des_limpa,rio_marker,climate_component ,activity_landscape ),by = c("acao"="acao_des_limpa")) 
# Filtro do Ajuste 5 (FOI APLICADO A AJUSTE 5 POIES ELE ESTA CERTO)
data_siop_final_landscape2 <- data_siop_final_landscape2 %>%
  mutate(rio_marker = case_when(plano_orc == "licenca, avaliacao , registro e autorizacoes ambientais" ~ 0.4,
                                plano_orc == "licenca, avaliacao, registro e autorizacoes ambientais" ~ 0.4,
                                plano_orc == "rastreio e controle de satelites" ~ 0.4,
                                plano_orc == "recepcao, armazenamento, processamento e distribuicao de dados de satelites"~0.4,
                                plano_orc == "apoio ao desenvolvimento sustentavel das cadeias produtivas agricolas"~0.4,
                                plano_orc == "fomento a indicacao geografica de produtos agropecuarios - ig"~0.4,
                                plano_orc == "funcionamento do conselho nacional de recursos hidricos"~0.4,
                                .default = rio_marker)) 
#Filtro de Ajuste 4 (FOI APLICADO O AJUSETE 4 POIS ELE ESTA CERTO TBM)
data_siop_final_landscape2 <- data_siop_final_landscape2 %>% 
  mutate(rio_marker = case_when(plano_orc=="desenvolvimento dos satelites da serie amazonia"~1,
                                plano_orc == "desenvolvimento dos satelites da serie amazonia - regra de ouro"~1,
                                .default = rio_marker)) 
  


data_siop_final_landscape2

# Aplicacao Rio Marker
data_siop_final_landscape2 <- data_siop_final_landscape2 %>% mutate(value_original_currency = value_original_currency*rio_marker)
data_siop_final_landscape2$value_original_currency %>% sum #16.913.371.927

# Alguns outros problemas dessa metodologia:
# Planos orcamentarios, como do INPE, foram embora
# Não há Administração da Unidade;Capacitação de Recursos Humanos no INPE
data_siop_final_landscape2 %>% filter(acao == "administracao da unidade") %>% select(plano_orc) %>% unique %>% view
# Ja esta um pouco melhor
```



